/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AuthInviteRouteImport } from './routes/auth/invite'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminAppointmentsIndexRouteImport } from './routes/admin/appointments/index'
import { Route as AdminAppointmentsIdRouteImport } from './routes/admin/appointments/$id'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin/articles/index'
import { Route as AdminArticlesIdRouteImport } from './routes/admin/articles/$id'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminCategoriesIdRouteImport } from './routes/admin/categories/$id'
import { Route as AdminFaqsIndexRouteImport } from './routes/admin/faqs/index'
import { Route as AdminFaqsIdRouteImport } from './routes/admin/faqs/$id'
import { Route as AdminMessagesIndexRouteImport } from './routes/admin/messages/index'
import { Route as AdminMessagesIdRouteImport } from './routes/admin/messages/$id'
import { Route as AdminNewsletterIndexRouteImport } from './routes/admin/newsletter/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminProjectsIdRouteImport } from './routes/admin/projects/$id'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminReportsIdRouteImport } from './routes/admin/reports/$id'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin/reviews/index'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services/index'
import { Route as AdminServicesIdRouteImport } from './routes/admin/services/$id'
import { Route as AdminShortlinksIndexRouteImport } from './routes/admin/shortlinks/index'
import { Route as AdminShortlinksIdRouteImport } from './routes/admin/shortlinks/$id'
import { Route as AdminStatsIndexRouteImport } from './routes/admin/stats/index'
import { Route as AdminStatsIdRouteImport } from './routes/admin/stats/$id'
import { Route as AdminTestimonialsIndexRouteImport } from './routes/admin/testimonials/index'
import { Route as AdminTestimonialsIdRouteImport } from './routes/admin/testimonials/$id'
import { Route as AdminTrainingsIndexRouteImport } from './routes/admin/trainings/index'
import { Route as AdminTrainingsIdRouteImport } from './routes/admin/trainings/$id'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminMembersAdminsIndexRouteImport } from './routes/admin/members/admins/index'
import { Route as AdminMembersAdminsIdRouteImport } from './routes/admin/members/admins/$id'
import { Route as AdminMembersStudentsIndexRouteImport } from './routes/admin/members/students/index'
import { Route as AdminMembersStudentsIdRouteImport } from './routes/admin/members/students/$id'
import { Route as AdminMembersUsersIndexRouteImport } from './routes/admin/members/users/index'
import { Route as AdminMembersUsersIdRouteImport } from './routes/admin/members/users/$id'
import { Route as AdminNewsletterCampaignsIndexRouteImport } from './routes/admin/newsletter/campaigns/index'
import { Route as AdminNewsletterCampaignsIdRouteImport } from './routes/admin/newsletter/campaigns/$id'
import { Route as AdminNewsletterSubscribersIndexRouteImport } from './routes/admin/newsletter/subscribers/index'
import { Route as AdminNewsletterSubscribersIdRouteImport } from './routes/admin/newsletter/subscribers/$id'
import { Route as AdminReviewsFormsIndexRouteImport } from './routes/admin/reviews/forms/index'
import { Route as AdminReviewsFormsIdRouteImport } from './routes/admin/reviews/forms/$id'
import { Route as AdminReviewsInvitesIndexRouteImport } from './routes/admin/reviews/invites/index'
import { Route as AdminReviewsInvitesIdRouteImport } from './routes/admin/reviews/invites/$id'
import { Route as AdminReviewsResponsesIndexRouteImport } from './routes/admin/reviews/responses/index'
import { Route as AdminReviewsResponsesIdRouteImport } from './routes/admin/reviews/responses/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/auth/invite',
  path: '/auth/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsIndexRoute = AdminAppointmentsIndexRouteImport.update({
  id: '/admin/appointments/',
  path: '/admin/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsIdRoute = AdminAppointmentsIdRouteImport.update({
  id: '/admin/appointments/$id',
  path: '/admin/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/admin/articles/',
  path: '/admin/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/admin/articles/$id',
  path: '/admin/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/admin/categories/',
  path: '/admin/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesIdRoute = AdminCategoriesIdRouteImport.update({
  id: '/admin/categories/$id',
  path: '/admin/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsIndexRoute = AdminFaqsIndexRouteImport.update({
  id: '/admin/faqs/',
  path: '/admin/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqsIdRoute = AdminFaqsIdRouteImport.update({
  id: '/admin/faqs/$id',
  path: '/admin/faqs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesIndexRoute = AdminMessagesIndexRouteImport.update({
  id: '/admin/messages/',
  path: '/admin/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesIdRoute = AdminMessagesIdRouteImport.update({
  id: '/admin/messages/$id',
  path: '/admin/messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterIndexRoute = AdminNewsletterIndexRouteImport.update({
  id: '/admin/newsletter/',
  path: '/admin/newsletter/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/admin/projects/$id',
  path: '/admin/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/admin/reports/',
  path: '/admin/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsIdRoute = AdminReportsIdRouteImport.update({
  id: '/admin/reports/$id',
  path: '/admin/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/admin/reviews/',
  path: '/admin/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/admin/services/',
  path: '/admin/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesIdRoute = AdminServicesIdRouteImport.update({
  id: '/admin/services/$id',
  path: '/admin/services/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShortlinksIndexRoute = AdminShortlinksIndexRouteImport.update({
  id: '/admin/shortlinks/',
  path: '/admin/shortlinks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShortlinksIdRoute = AdminShortlinksIdRouteImport.update({
  id: '/admin/shortlinks/$id',
  path: '/admin/shortlinks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsIndexRoute = AdminStatsIndexRouteImport.update({
  id: '/admin/stats/',
  path: '/admin/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsIdRoute = AdminStatsIdRouteImport.update({
  id: '/admin/stats/$id',
  path: '/admin/stats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsIndexRoute = AdminTestimonialsIndexRouteImport.update({
  id: '/admin/testimonials/',
  path: '/admin/testimonials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsIdRoute = AdminTestimonialsIdRouteImport.update({
  id: '/admin/testimonials/$id',
  path: '/admin/testimonials/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingsIndexRoute = AdminTrainingsIndexRouteImport.update({
  id: '/admin/trainings/',
  path: '/admin/trainings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingsIdRoute = AdminTrainingsIdRouteImport.update({
  id: '/admin/trainings/$id',
  path: '/admin/trainings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersAdminsIndexRoute = AdminMembersAdminsIndexRouteImport.update({
  id: '/admin/members/admins/',
  path: '/admin/members/admins/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersAdminsIdRoute = AdminMembersAdminsIdRouteImport.update({
  id: '/admin/members/admins/$id',
  path: '/admin/members/admins/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersStudentsIndexRoute =
  AdminMembersStudentsIndexRouteImport.update({
    id: '/admin/members/students/',
    path: '/admin/members/students/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMembersStudentsIdRoute = AdminMembersStudentsIdRouteImport.update({
  id: '/admin/members/students/$id',
  path: '/admin/members/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersUsersIndexRoute = AdminMembersUsersIndexRouteImport.update({
  id: '/admin/members/users/',
  path: '/admin/members/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersUsersIdRoute = AdminMembersUsersIdRouteImport.update({
  id: '/admin/members/users/$id',
  path: '/admin/members/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterCampaignsIndexRoute =
  AdminNewsletterCampaignsIndexRouteImport.update({
    id: '/admin/newsletter/campaigns/',
    path: '/admin/newsletter/campaigns/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNewsletterCampaignsIdRoute =
  AdminNewsletterCampaignsIdRouteImport.update({
    id: '/admin/newsletter/campaigns/$id',
    path: '/admin/newsletter/campaigns/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNewsletterSubscribersIndexRoute =
  AdminNewsletterSubscribersIndexRouteImport.update({
    id: '/admin/newsletter/subscribers/',
    path: '/admin/newsletter/subscribers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminNewsletterSubscribersIdRoute =
  AdminNewsletterSubscribersIdRouteImport.update({
    id: '/admin/newsletter/subscribers/$id',
    path: '/admin/newsletter/subscribers/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReviewsFormsIndexRoute = AdminReviewsFormsIndexRouteImport.update({
  id: '/admin/reviews/forms/',
  path: '/admin/reviews/forms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsFormsIdRoute = AdminReviewsFormsIdRouteImport.update({
  id: '/admin/reviews/forms/$id',
  path: '/admin/reviews/forms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsInvitesIndexRoute =
  AdminReviewsInvitesIndexRouteImport.update({
    id: '/admin/reviews/invites/',
    path: '/admin/reviews/invites/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReviewsInvitesIdRoute = AdminReviewsInvitesIdRouteImport.update({
  id: '/admin/reviews/invites/$id',
  path: '/admin/reviews/invites/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsResponsesIndexRoute =
  AdminReviewsResponsesIndexRouteImport.update({
    id: '/admin/reviews/responses/',
    path: '/admin/reviews/responses/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminReviewsResponsesIdRoute = AdminReviewsResponsesIdRouteImport.update({
  id: '/admin/reviews/responses/$id',
  path: '/admin/reviews/responses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/messages/$id': typeof AdminMessagesIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/shortlinks/$id': typeof AdminShortlinksIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/admin/trainings/$id': typeof AdminTrainingsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/faqs/': typeof AdminFaqsIndexRoute
  '/admin/messages/': typeof AdminMessagesIndexRoute
  '/admin/newsletter/': typeof AdminNewsletterIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/shortlinks/': typeof AdminShortlinksIndexRoute
  '/admin/stats/': typeof AdminStatsIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
  '/admin/trainings/': typeof AdminTrainingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/members/admins/$id': typeof AdminMembersAdminsIdRoute
  '/admin/members/students/$id': typeof AdminMembersStudentsIdRoute
  '/admin/members/users/$id': typeof AdminMembersUsersIdRoute
  '/admin/newsletter/campaigns/$id': typeof AdminNewsletterCampaignsIdRoute
  '/admin/newsletter/subscribers/$id': typeof AdminNewsletterSubscribersIdRoute
  '/admin/reviews/forms/$id': typeof AdminReviewsFormsIdRoute
  '/admin/reviews/invites/$id': typeof AdminReviewsInvitesIdRoute
  '/admin/reviews/responses/$id': typeof AdminReviewsResponsesIdRoute
  '/admin/members/admins/': typeof AdminMembersAdminsIndexRoute
  '/admin/members/students/': typeof AdminMembersStudentsIndexRoute
  '/admin/members/users/': typeof AdminMembersUsersIndexRoute
  '/admin/newsletter/campaigns/': typeof AdminNewsletterCampaignsIndexRoute
  '/admin/newsletter/subscribers/': typeof AdminNewsletterSubscribersIndexRoute
  '/admin/reviews/forms/': typeof AdminReviewsFormsIndexRoute
  '/admin/reviews/invites/': typeof AdminReviewsInvitesIndexRoute
  '/admin/reviews/responses/': typeof AdminReviewsResponsesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/messages/$id': typeof AdminMessagesIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/shortlinks/$id': typeof AdminShortlinksIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/admin/trainings/$id': typeof AdminTrainingsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/appointments': typeof AdminAppointmentsIndexRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/faqs': typeof AdminFaqsIndexRoute
  '/admin/messages': typeof AdminMessagesIndexRoute
  '/admin/newsletter': typeof AdminNewsletterIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/shortlinks': typeof AdminShortlinksIndexRoute
  '/admin/stats': typeof AdminStatsIndexRoute
  '/admin/testimonials': typeof AdminTestimonialsIndexRoute
  '/admin/trainings': typeof AdminTrainingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/members/admins/$id': typeof AdminMembersAdminsIdRoute
  '/admin/members/students/$id': typeof AdminMembersStudentsIdRoute
  '/admin/members/users/$id': typeof AdminMembersUsersIdRoute
  '/admin/newsletter/campaigns/$id': typeof AdminNewsletterCampaignsIdRoute
  '/admin/newsletter/subscribers/$id': typeof AdminNewsletterSubscribersIdRoute
  '/admin/reviews/forms/$id': typeof AdminReviewsFormsIdRoute
  '/admin/reviews/invites/$id': typeof AdminReviewsInvitesIdRoute
  '/admin/reviews/responses/$id': typeof AdminReviewsResponsesIdRoute
  '/admin/members/admins': typeof AdminMembersAdminsIndexRoute
  '/admin/members/students': typeof AdminMembersStudentsIndexRoute
  '/admin/members/users': typeof AdminMembersUsersIndexRoute
  '/admin/newsletter/campaigns': typeof AdminNewsletterCampaignsIndexRoute
  '/admin/newsletter/subscribers': typeof AdminNewsletterSubscribersIndexRoute
  '/admin/reviews/forms': typeof AdminReviewsFormsIndexRoute
  '/admin/reviews/invites': typeof AdminReviewsInvitesIndexRoute
  '/admin/reviews/responses': typeof AdminReviewsResponsesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/profile': typeof AdminProfileRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/appointments/$id': typeof AdminAppointmentsIdRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/categories/$id': typeof AdminCategoriesIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/messages/$id': typeof AdminMessagesIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/reports/$id': typeof AdminReportsIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/shortlinks/$id': typeof AdminShortlinksIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/admin/trainings/$id': typeof AdminTrainingsIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/appointments/': typeof AdminAppointmentsIndexRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/faqs/': typeof AdminFaqsIndexRoute
  '/admin/messages/': typeof AdminMessagesIndexRoute
  '/admin/newsletter/': typeof AdminNewsletterIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/shortlinks/': typeof AdminShortlinksIndexRoute
  '/admin/stats/': typeof AdminStatsIndexRoute
  '/admin/testimonials/': typeof AdminTestimonialsIndexRoute
  '/admin/trainings/': typeof AdminTrainingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/members/admins/$id': typeof AdminMembersAdminsIdRoute
  '/admin/members/students/$id': typeof AdminMembersStudentsIdRoute
  '/admin/members/users/$id': typeof AdminMembersUsersIdRoute
  '/admin/newsletter/campaigns/$id': typeof AdminNewsletterCampaignsIdRoute
  '/admin/newsletter/subscribers/$id': typeof AdminNewsletterSubscribersIdRoute
  '/admin/reviews/forms/$id': typeof AdminReviewsFormsIdRoute
  '/admin/reviews/invites/$id': typeof AdminReviewsInvitesIdRoute
  '/admin/reviews/responses/$id': typeof AdminReviewsResponsesIdRoute
  '/admin/members/admins/': typeof AdminMembersAdminsIndexRoute
  '/admin/members/students/': typeof AdminMembersStudentsIndexRoute
  '/admin/members/users/': typeof AdminMembersUsersIndexRoute
  '/admin/newsletter/campaigns/': typeof AdminNewsletterCampaignsIndexRoute
  '/admin/newsletter/subscribers/': typeof AdminNewsletterSubscribersIndexRoute
  '/admin/reviews/forms/': typeof AdminReviewsFormsIndexRoute
  '/admin/reviews/invites/': typeof AdminReviewsInvitesIndexRoute
  '/admin/reviews/responses/': typeof AdminReviewsResponsesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/profile'
    | '/auth/invite'
    | '/auth/login'
    | '/admin/'
    | '/admin/appointments/$id'
    | '/admin/articles/$id'
    | '/admin/categories/$id'
    | '/admin/faqs/$id'
    | '/admin/messages/$id'
    | '/admin/projects/$id'
    | '/admin/reports/$id'
    | '/admin/services/$id'
    | '/admin/shortlinks/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
    | '/admin/trainings/$id'
    | '/admin/users/$id'
    | '/admin/appointments/'
    | '/admin/articles/'
    | '/admin/categories/'
    | '/admin/faqs/'
    | '/admin/messages/'
    | '/admin/newsletter/'
    | '/admin/projects/'
    | '/admin/reports/'
    | '/admin/reviews/'
    | '/admin/services/'
    | '/admin/shortlinks/'
    | '/admin/stats/'
    | '/admin/testimonials/'
    | '/admin/trainings/'
    | '/admin/users/'
    | '/admin/members/admins/$id'
    | '/admin/members/students/$id'
    | '/admin/members/users/$id'
    | '/admin/newsletter/campaigns/$id'
    | '/admin/newsletter/subscribers/$id'
    | '/admin/reviews/forms/$id'
    | '/admin/reviews/invites/$id'
    | '/admin/reviews/responses/$id'
    | '/admin/members/admins/'
    | '/admin/members/students/'
    | '/admin/members/users/'
    | '/admin/newsletter/campaigns/'
    | '/admin/newsletter/subscribers/'
    | '/admin/reviews/forms/'
    | '/admin/reviews/invites/'
    | '/admin/reviews/responses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/profile'
    | '/auth/invite'
    | '/auth/login'
    | '/admin'
    | '/admin/appointments/$id'
    | '/admin/articles/$id'
    | '/admin/categories/$id'
    | '/admin/faqs/$id'
    | '/admin/messages/$id'
    | '/admin/projects/$id'
    | '/admin/reports/$id'
    | '/admin/services/$id'
    | '/admin/shortlinks/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
    | '/admin/trainings/$id'
    | '/admin/users/$id'
    | '/admin/appointments'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/faqs'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/shortlinks'
    | '/admin/stats'
    | '/admin/testimonials'
    | '/admin/trainings'
    | '/admin/users'
    | '/admin/members/admins/$id'
    | '/admin/members/students/$id'
    | '/admin/members/users/$id'
    | '/admin/newsletter/campaigns/$id'
    | '/admin/newsletter/subscribers/$id'
    | '/admin/reviews/forms/$id'
    | '/admin/reviews/invites/$id'
    | '/admin/reviews/responses/$id'
    | '/admin/members/admins'
    | '/admin/members/students'
    | '/admin/members/users'
    | '/admin/newsletter/campaigns'
    | '/admin/newsletter/subscribers'
    | '/admin/reviews/forms'
    | '/admin/reviews/invites'
    | '/admin/reviews/responses'
  id:
    | '__root__'
    | '/'
    | '/admin/profile'
    | '/auth/invite'
    | '/auth/login'
    | '/admin/'
    | '/admin/appointments/$id'
    | '/admin/articles/$id'
    | '/admin/categories/$id'
    | '/admin/faqs/$id'
    | '/admin/messages/$id'
    | '/admin/projects/$id'
    | '/admin/reports/$id'
    | '/admin/services/$id'
    | '/admin/shortlinks/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
    | '/admin/trainings/$id'
    | '/admin/users/$id'
    | '/admin/appointments/'
    | '/admin/articles/'
    | '/admin/categories/'
    | '/admin/faqs/'
    | '/admin/messages/'
    | '/admin/newsletter/'
    | '/admin/projects/'
    | '/admin/reports/'
    | '/admin/reviews/'
    | '/admin/services/'
    | '/admin/shortlinks/'
    | '/admin/stats/'
    | '/admin/testimonials/'
    | '/admin/trainings/'
    | '/admin/users/'
    | '/admin/members/admins/$id'
    | '/admin/members/students/$id'
    | '/admin/members/users/$id'
    | '/admin/newsletter/campaigns/$id'
    | '/admin/newsletter/subscribers/$id'
    | '/admin/reviews/forms/$id'
    | '/admin/reviews/invites/$id'
    | '/admin/reviews/responses/$id'
    | '/admin/members/admins/'
    | '/admin/members/students/'
    | '/admin/members/users/'
    | '/admin/newsletter/campaigns/'
    | '/admin/newsletter/subscribers/'
    | '/admin/reviews/forms/'
    | '/admin/reviews/invites/'
    | '/admin/reviews/responses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAppointmentsIdRoute: typeof AdminAppointmentsIdRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminCategoriesIdRoute: typeof AdminCategoriesIdRoute
  AdminFaqsIdRoute: typeof AdminFaqsIdRoute
  AdminMessagesIdRoute: typeof AdminMessagesIdRoute
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminReportsIdRoute: typeof AdminReportsIdRoute
  AdminServicesIdRoute: typeof AdminServicesIdRoute
  AdminShortlinksIdRoute: typeof AdminShortlinksIdRoute
  AdminStatsIdRoute: typeof AdminStatsIdRoute
  AdminTestimonialsIdRoute: typeof AdminTestimonialsIdRoute
  AdminTrainingsIdRoute: typeof AdminTrainingsIdRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminAppointmentsIndexRoute: typeof AdminAppointmentsIndexRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminFaqsIndexRoute: typeof AdminFaqsIndexRoute
  AdminMessagesIndexRoute: typeof AdminMessagesIndexRoute
  AdminNewsletterIndexRoute: typeof AdminNewsletterIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminShortlinksIndexRoute: typeof AdminShortlinksIndexRoute
  AdminStatsIndexRoute: typeof AdminStatsIndexRoute
  AdminTestimonialsIndexRoute: typeof AdminTestimonialsIndexRoute
  AdminTrainingsIndexRoute: typeof AdminTrainingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminMembersAdminsIdRoute: typeof AdminMembersAdminsIdRoute
  AdminMembersStudentsIdRoute: typeof AdminMembersStudentsIdRoute
  AdminMembersUsersIdRoute: typeof AdminMembersUsersIdRoute
  AdminNewsletterCampaignsIdRoute: typeof AdminNewsletterCampaignsIdRoute
  AdminNewsletterSubscribersIdRoute: typeof AdminNewsletterSubscribersIdRoute
  AdminReviewsFormsIdRoute: typeof AdminReviewsFormsIdRoute
  AdminReviewsInvitesIdRoute: typeof AdminReviewsInvitesIdRoute
  AdminReviewsResponsesIdRoute: typeof AdminReviewsResponsesIdRoute
  AdminMembersAdminsIndexRoute: typeof AdminMembersAdminsIndexRoute
  AdminMembersStudentsIndexRoute: typeof AdminMembersStudentsIndexRoute
  AdminMembersUsersIndexRoute: typeof AdminMembersUsersIndexRoute
  AdminNewsletterCampaignsIndexRoute: typeof AdminNewsletterCampaignsIndexRoute
  AdminNewsletterSubscribersIndexRoute: typeof AdminNewsletterSubscribersIndexRoute
  AdminReviewsFormsIndexRoute: typeof AdminReviewsFormsIndexRoute
  AdminReviewsInvitesIndexRoute: typeof AdminReviewsInvitesIndexRoute
  AdminReviewsResponsesIndexRoute: typeof AdminReviewsResponsesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/auth/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments/': {
      id: '/admin/appointments/'
      path: '/admin/appointments'
      fullPath: '/admin/appointments/'
      preLoaderRoute: typeof AdminAppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments/$id': {
      id: '/admin/appointments/$id'
      path: '/admin/appointments/$id'
      fullPath: '/admin/appointments/$id'
      preLoaderRoute: typeof AdminAppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/admin/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/$id': {
      id: '/admin/categories/$id'
      path: '/admin/categories/$id'
      fullPath: '/admin/categories/$id'
      preLoaderRoute: typeof AdminCategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs/': {
      id: '/admin/faqs/'
      path: '/admin/faqs'
      fullPath: '/admin/faqs/'
      preLoaderRoute: typeof AdminFaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faqs/$id': {
      id: '/admin/faqs/$id'
      path: '/admin/faqs/$id'
      fullPath: '/admin/faqs/$id'
      preLoaderRoute: typeof AdminFaqsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages/': {
      id: '/admin/messages/'
      path: '/admin/messages'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AdminMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages/$id': {
      id: '/admin/messages/$id'
      path: '/admin/messages/$id'
      fullPath: '/admin/messages/$id'
      preLoaderRoute: typeof AdminMessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter/': {
      id: '/admin/newsletter/'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter/'
      preLoaderRoute: typeof AdminNewsletterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/admin/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports/$id': {
      id: '/admin/reports/$id'
      path: '/admin/reports/$id'
      fullPath: '/admin/reports/$id'
      preLoaderRoute: typeof AdminReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/admin/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/admin/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services/$id': {
      id: '/admin/services/$id'
      path: '/admin/services/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminServicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shortlinks/': {
      id: '/admin/shortlinks/'
      path: '/admin/shortlinks'
      fullPath: '/admin/shortlinks/'
      preLoaderRoute: typeof AdminShortlinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shortlinks/$id': {
      id: '/admin/shortlinks/$id'
      path: '/admin/shortlinks/$id'
      fullPath: '/admin/shortlinks/$id'
      preLoaderRoute: typeof AdminShortlinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats/': {
      id: '/admin/stats/'
      path: '/admin/stats'
      fullPath: '/admin/stats/'
      preLoaderRoute: typeof AdminStatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats/$id': {
      id: '/admin/stats/$id'
      path: '/admin/stats/$id'
      fullPath: '/admin/stats/$id'
      preLoaderRoute: typeof AdminStatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials/': {
      id: '/admin/testimonials/'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials/'
      preLoaderRoute: typeof AdminTestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials/$id': {
      id: '/admin/testimonials/$id'
      path: '/admin/testimonials/$id'
      fullPath: '/admin/testimonials/$id'
      preLoaderRoute: typeof AdminTestimonialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainings/': {
      id: '/admin/trainings/'
      path: '/admin/trainings'
      fullPath: '/admin/trainings/'
      preLoaderRoute: typeof AdminTrainingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trainings/$id': {
      id: '/admin/trainings/$id'
      path: '/admin/trainings/$id'
      fullPath: '/admin/trainings/$id'
      preLoaderRoute: typeof AdminTrainingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/admins/': {
      id: '/admin/members/admins/'
      path: '/admin/members/admins'
      fullPath: '/admin/members/admins/'
      preLoaderRoute: typeof AdminMembersAdminsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/admins/$id': {
      id: '/admin/members/admins/$id'
      path: '/admin/members/admins/$id'
      fullPath: '/admin/members/admins/$id'
      preLoaderRoute: typeof AdminMembersAdminsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/students/': {
      id: '/admin/members/students/'
      path: '/admin/members/students'
      fullPath: '/admin/members/students/'
      preLoaderRoute: typeof AdminMembersStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/students/$id': {
      id: '/admin/members/students/$id'
      path: '/admin/members/students/$id'
      fullPath: '/admin/members/students/$id'
      preLoaderRoute: typeof AdminMembersStudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/users/': {
      id: '/admin/members/users/'
      path: '/admin/members/users'
      fullPath: '/admin/members/users/'
      preLoaderRoute: typeof AdminMembersUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members/users/$id': {
      id: '/admin/members/users/$id'
      path: '/admin/members/users/$id'
      fullPath: '/admin/members/users/$id'
      preLoaderRoute: typeof AdminMembersUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter/campaigns/': {
      id: '/admin/newsletter/campaigns/'
      path: '/admin/newsletter/campaigns'
      fullPath: '/admin/newsletter/campaigns/'
      preLoaderRoute: typeof AdminNewsletterCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter/campaigns/$id': {
      id: '/admin/newsletter/campaigns/$id'
      path: '/admin/newsletter/campaigns/$id'
      fullPath: '/admin/newsletter/campaigns/$id'
      preLoaderRoute: typeof AdminNewsletterCampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter/subscribers/': {
      id: '/admin/newsletter/subscribers/'
      path: '/admin/newsletter/subscribers'
      fullPath: '/admin/newsletter/subscribers/'
      preLoaderRoute: typeof AdminNewsletterSubscribersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter/subscribers/$id': {
      id: '/admin/newsletter/subscribers/$id'
      path: '/admin/newsletter/subscribers/$id'
      fullPath: '/admin/newsletter/subscribers/$id'
      preLoaderRoute: typeof AdminNewsletterSubscribersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews/forms/': {
      id: '/admin/reviews/forms/'
      path: '/admin/reviews/forms'
      fullPath: '/admin/reviews/forms/'
      preLoaderRoute: typeof AdminReviewsFormsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews/forms/$id': {
      id: '/admin/reviews/forms/$id'
      path: '/admin/reviews/forms/$id'
      fullPath: '/admin/reviews/forms/$id'
      preLoaderRoute: typeof AdminReviewsFormsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews/invites/': {
      id: '/admin/reviews/invites/'
      path: '/admin/reviews/invites'
      fullPath: '/admin/reviews/invites/'
      preLoaderRoute: typeof AdminReviewsInvitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews/invites/$id': {
      id: '/admin/reviews/invites/$id'
      path: '/admin/reviews/invites/$id'
      fullPath: '/admin/reviews/invites/$id'
      preLoaderRoute: typeof AdminReviewsInvitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews/responses/': {
      id: '/admin/reviews/responses/'
      path: '/admin/reviews/responses'
      fullPath: '/admin/reviews/responses/'
      preLoaderRoute: typeof AdminReviewsResponsesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews/responses/$id': {
      id: '/admin/reviews/responses/$id'
      path: '/admin/reviews/responses/$id'
      fullPath: '/admin/reviews/responses/$id'
      preLoaderRoute: typeof AdminReviewsResponsesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminProfileRoute: AdminProfileRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAppointmentsIdRoute: AdminAppointmentsIdRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminCategoriesIdRoute: AdminCategoriesIdRoute,
  AdminFaqsIdRoute: AdminFaqsIdRoute,
  AdminMessagesIdRoute: AdminMessagesIdRoute,
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminReportsIdRoute: AdminReportsIdRoute,
  AdminServicesIdRoute: AdminServicesIdRoute,
  AdminShortlinksIdRoute: AdminShortlinksIdRoute,
  AdminStatsIdRoute: AdminStatsIdRoute,
  AdminTestimonialsIdRoute: AdminTestimonialsIdRoute,
  AdminTrainingsIdRoute: AdminTrainingsIdRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminAppointmentsIndexRoute: AdminAppointmentsIndexRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminFaqsIndexRoute: AdminFaqsIndexRoute,
  AdminMessagesIndexRoute: AdminMessagesIndexRoute,
  AdminNewsletterIndexRoute: AdminNewsletterIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminShortlinksIndexRoute: AdminShortlinksIndexRoute,
  AdminStatsIndexRoute: AdminStatsIndexRoute,
  AdminTestimonialsIndexRoute: AdminTestimonialsIndexRoute,
  AdminTrainingsIndexRoute: AdminTrainingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminMembersAdminsIdRoute: AdminMembersAdminsIdRoute,
  AdminMembersStudentsIdRoute: AdminMembersStudentsIdRoute,
  AdminMembersUsersIdRoute: AdminMembersUsersIdRoute,
  AdminNewsletterCampaignsIdRoute: AdminNewsletterCampaignsIdRoute,
  AdminNewsletterSubscribersIdRoute: AdminNewsletterSubscribersIdRoute,
  AdminReviewsFormsIdRoute: AdminReviewsFormsIdRoute,
  AdminReviewsInvitesIdRoute: AdminReviewsInvitesIdRoute,
  AdminReviewsResponsesIdRoute: AdminReviewsResponsesIdRoute,
  AdminMembersAdminsIndexRoute: AdminMembersAdminsIndexRoute,
  AdminMembersStudentsIndexRoute: AdminMembersStudentsIndexRoute,
  AdminMembersUsersIndexRoute: AdminMembersUsersIndexRoute,
  AdminNewsletterCampaignsIndexRoute: AdminNewsletterCampaignsIndexRoute,
  AdminNewsletterSubscribersIndexRoute: AdminNewsletterSubscribersIndexRoute,
  AdminReviewsFormsIndexRoute: AdminReviewsFormsIndexRoute,
  AdminReviewsInvitesIndexRoute: AdminReviewsInvitesIndexRoute,
  AdminReviewsResponsesIndexRoute: AdminReviewsResponsesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
